/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

const compoundsMap: Record<string, string> = {
    // === Irregular readings (not compositional) ===
    "今日": "kyou",
    "昨日": "kinou",
    "明日": "ashita",
    "一昨日": "ototoi",
    "明後日": "asatte",
    "大人": "otona",
    "友達": "tomodachi",
    "恋人": "koibito",
    "彼氏": "kareshi",
    "彼女": "kanojo",
    "一人": "hitori",
    "二人": "futari",
    "自分": "jibun",
    "一応": "ichio",
    "沢山": "takusan",
    "沢山の": "takusanno",

    // === Rendaku (sequential voicing) compounds ===
    "頑張る": "ganbaru",
    "頑張って": "ganbatte",
    "頑張れ": "ganbare",
    "頑張ろう": "ganbarou",
    "頑張ります": "ganbarimasu",
    "頑張らない": "ganbaranai",
    "手伝う": "tetsudau",
    "手伝って": "tetsudatte",
    "手伝い": "tetsudai",
    "手伝います": "tetsudaimasu",
    "話し合う": "hanashiau",
    "話し合って": "hanashiatte",
    "持ち帰る": "mochikaeru",
    "持ち帰って": "mochikaette",
    "引っ越す": "hikkosu",
    "引っ越して": "hikkoshite",
    "引っ越し": "hikkoshi",
    "繰り返す": "kurikaesu",
    "繰り返して": "kurikaeshite",
    "立ち上がる": "tachiagaru",
    "飛び出す": "tobidasu",
    "飛び出して": "tobidashite",
    "思い出す": "omoidasu",
    "思い出して": "omoidashite",
    "見つける": "mitsukeru",
    "見つけて": "mitsukete",
    "見つかる": "mitsukaru",
    "近づく": "chikazuku",
    "近づいて": "chikazuite",
    "作り出す": "tsukuridasu",
    "書き込む": "kakikomu",
    "書き込んで": "kakikonde",
    "落ち着く": "ochitsuku",
    "落ち着いて": "ochitsuite",

    // === Common two-kanji words with specific readings ===
    "情報": "jouhou",
    "電話": "denwa",
    "住所": "juusho",
    "名前": "namae",
    "誕生日": "tanjoubi",
    "学校": "gakkou",
    "先生": "sensei",
    "学生": "gakusei",
    "勉強": "benkyou",
    "勉強して": "benkyoushite",
    "家族": "kazoku",
    "兄弟": "kyoudai",
    "会社": "kaisha",
    "仕事": "shigoto",
    "趣味": "shumi",
    "理由": "riyuu",
    "方法": "houhou",
    "天気": "tenki",
    "気持ち": "kimochi",
    "気分": "kibun",
    "気温": "kion",
    "時間": "jikan",
    "約束": "yakusoku",
    "約束して": "yakusokushite",
    "返事": "henji",
    "返事して": "henjishite",
    "連絡": "renraku",
    "連絡して": "renrakushite",
    "大丈夫": "daijoubu",
    "大変": "taihen",
    "大切": "taisetsu",
    "大好き": "daisuki",
    "大嫌い": "daikirai",
    "一番": "ichiban",
    "一緒": "issho",
    "色々": "iroiro",
    "失礼": "shitsurei",
    "失礼します": "shitsureishimasu",
    "本当": "hontou",
    "本当に": "hontouni",
    "毎日": "mainichi",
    "毎週": "maishuu",
    "今年": "kotoshi",
    "去年": "kyonen",
    "来年": "rainen",
    "来週": "raishuu",
    "先週": "senshuu",
    "今週": "konshuu",

    // === Counters and numbers (multi-character) ===
    "一つ": "hitotsu",
    "二つ": "futatsu",
    "三つ": "mittsu",
    "四つ": "yottsu",
    "五つ": "itsutsu",
    "六つ": "muttsu",
    "七つ": "nanatsu",
    "八つ": "yattsu",
    "九つ": "kokonotsu",
    "十": "juu",
    "何人": "nannin",
    "幾つ": "ikutsu",
    "幾日": "ikunichi",

    // === Question / indefinite words (multi-kanji or kanji+kana) ===
    "何時": "nanji",
    "何故": "naze",
    "何曜日": "nanyoubi",
    "何方": "donata",
    "何処": "doko",
    "何れ": "dore",
    "何の": "dono",
    "何か": "nanika",
    "何も": "nanimo",
    "誰か": "dareka",
    "誰も": "daremo",
    "幾何": "kura",

    // === Places / facilities ===
    "駅前": "ekimae",
    "病院": "byouin",
    "図書館": "toshokan",
    "博物館": "hakubutsukan",
    "美術館": "bijutsukan",
    "教室": "kyoushitsu",
    "体育館": "taiikukan",
    "銀行": "ginkou",
    "郵便局": "yuubinkyoku",
    "交番": "kouban",
    "神社": "jinja",
    "教会": "kyoukai",
    "店員": "tenin",
    "社員": "shain",
    "会社員": "kaishain",
    "警察": "keisatsu",
    "市役所": "shiyakusho",

    // === Common set phrases (multi-character) ===
    "御願い": "onegai",
    "御願いします": "onegaishimasu",
    "御願い致します": "onegaitashimasu",
};

export function lookupCompound(text: string, pos: number): { match: string; reading: string; } | null {
    let best: { match: string; reading: string; } | null = null;
    let candidate = "";
    for (let i = pos; i < text.length; i++) {
        candidate += text[i];
        const reading = compoundsMap[candidate];
        if (reading) best = { match: candidate, reading };
    }
    return best;
}
